version: "2"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - vhost:/etc/nginx/vhost.d
      - conf:/etc/nginx/conf.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    # network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=mxschardt@gmail.com
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # network_mode: bridge

  ping-pong:
    build: ./ping-pong
    restart: always
    ports:
      - "91:80"
    environment:
      VIRTUAL_HOST: mxschardt.ru
      LETSENCRYPT_HOST: mxschardt.ru
      PORT: "80"
      MESSAGE: "ping!"
    command: "./bin"

volumes:
  vhost:
  conf:
  html:
  certs:
  acme:
